.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "README20160122\-77355\-5W7R7V" "" "January 2016" "" ""
 \fIhttps://badge\.fury\.io/rb/open\-remote\fR  \fIhttps://travis\-ci\.org/jeremywrnr/open\-remote\fR  \fIhttp://jeremywrnr\.com/mit\-license\fR
.
.P
open\-remote \- a simple git remote opening tool\.
.
.P
tested and works well for:
.
.IP "" 4
.
.nf

\- github
\- bitbucket
\- heroku
.
.fi
.
.IP "" 0
.
.P
if there are other git hosting websites that you would like to use this with, either let me know or make a pull request with the augmentation for that host\.
.
.SH "setup"
.
.nf

[sudo] gem install open\-remote
.
.fi
.
.P
making a git alias for \'git open\' in your \fB\.gitconfig\fR:
.
.IP "" 4
.
.nf

open\-remote \-\-alias
.
.fi
.
.IP "" 0
.
.P
removing the alias, if you don\'t want it anymore:
.
.IP "" 4
.
.nf

open\-remote \-\-unalias
.
.fi
.
.IP "" 0
.
.SH "usage"
.
.nf

git open
.
.fi
.
.P
opens the first git remote\. to open a specific remote, specify some part (or all) of the host name\. for example:
.
.IP "" 4
.
.nf

git open bit
git open bucket
git open bitbucket
.
.fi
.
.IP "" 0
.
.P
will all open the current repository\'s bitbucket remote in the browser\.
.
.SH "about"
the original idea for this came from my friend charlie \fIhttps://github\.com/clehner\fR who initially provided me with a simple git alias that would do the same, but it only worked for repos that were https and was not platform independent\. I was also inspired by the git\-up \fIhttps://github\.com/aanand/git\-up\fR ruby gem in how seamlessly it integrated with git\. Here is the original git alias (made to work on osx), which charlie wrote (plop it in your \.gitconfig, if you don\'t want to install a ruby gem to open your git remotes):
.
.IP "" 4
.
.nf

[alias]
    open\-remote = "!open $(git remote \-v $@ | grep \-o \'http\e\eS*\' | head \-1); :"
.
.fi
.
.IP "" 0
.
.SH "testing"
.
.nf

bundle || gem install bundler
rake
.
.fi

